// Package apidoc builds the OpenAPI 3 description of the HTTP API.
//
// Component schemas are REFLECTED from the model package structs (the same
// structs handlers return and tygo generates the frontend types from), so the
// documented response shapes can't drift from the code. The paths table
// (paths.go / paths_features.go) is hand-maintained. cmd/openapi-gen writes the
// result to backend/openapi.yaml; the CI test (openapi_test.go) regenerates and
// diffs it, and checks every registered route is documented.
package apidoc

import (
	"fmt"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3gen"
	"sigs.k8s.io/yaml"

	"app-suite/internal/version"
)

// Header is prepended to the generated YAML (documents that it is generated).
const Header = "# AUTO-GENERATED by `go run ./cmd/openapi-gen` — DO NOT EDIT BY HAND.\n" +
	"# Schemas are reflected from internal/model; paths come from internal/apidoc.\n" +
	"# Regenerate after changing a model struct or a route; CI checks this file is current.\n"

// Build assembles and validates the OpenAPI document.
func Build() (*openapi3.T, error) {
	doc := &openapi3.T{
		OpenAPI: "3.0.3",
		Info: &openapi3.Info{
			Title:       "Senpan App Suite API",
			Version:     version.Version,
			Description: apiDescription,
		},
		Servers: openapi3.Servers{
			{URL: "/", Description: "Same-origin (the SPA calls the API at the deployment root)"},
		},
		Components: &openapi3.Components{
			Schemas:         openapi3.Schemas{},
			SecuritySchemes: securitySchemes(),
		},
		Paths: openapi3.NewPaths(),
		Tags:  tags(),
	}

	for name, v := range modelTypes {
		ref, err := openapi3gen.NewSchemaRefForValue(v, doc.Components.Schemas, openapi3gen.UseAllExportedFields())
		if err != nil {
			return nil, fmt.Errorf("reflect %s: %w", name, err)
		}
		doc.Components.Schemas[name] = ref
	}
	doc.Components.Schemas["Error"] = openapi3.NewSchemaRef("", &openapi3.Schema{
		Type:       &openapi3.Types{"object"},
		Properties: openapi3.Schemas{"error": openapi3.NewSchemaRef("", openapi3.NewStringSchema())},
	})

	buildPaths(doc)

	if err := openapi3.NewLoader().ResolveRefsIn(doc, nil); err != nil {
		return nil, fmt.Errorf("resolve refs: %w", err)
	}
	if err := doc.Validate(openapi3.NewLoader().Context); err != nil {
		return nil, fmt.Errorf("spec invalid: %w", err)
	}
	return doc, nil
}

// YAML returns the document as YAML with the generated-file header.
func YAML() ([]byte, error) {
	doc, err := Build()
	if err != nil {
		return nil, err
	}
	jsonBytes, err := doc.MarshalJSON()
	if err != nil {
		return nil, fmt.Errorf("marshal json: %w", err)
	}
	data, err := yaml.JSONToYAML(jsonBytes)
	if err != nil {
		return nil, fmt.Errorf("json->yaml: %w", err)
	}
	return append([]byte(Header), data...), nil
}
